### ISSUE TITLE
#main randomly hangs

### ISSUE THREAD

**Issue by quackduck** [quackduck/devzat#76]
No idea why, no specific trigger I noticed

**Comment by Arkaeriit** [comment]
Maybe this is caused by the shear amount of people. Maybe we should make so that if more than 15 or so people are in `#main/`, the next people to join will be put in `#main_2/`. What do you think of that ?

**Comment by emma-miler** [comment]
Just noticed someone run `cat` without any arguments, and it froze immediately after. Could be related

**Comment by electronoob** [comment]
i think i caused it one time, just right now.. by running 'cat'.. i have no idea if that's what anyone else did prior.

**Comment by electronoob** [comment]
electronoob: cat
                                                                                  2m earlier
usage: cat [-benstuv] [file ...]

to be fair i don't think we are supposed to be able to execute shell commands anyway?

**Comment by Arkaeriit** [comment]
Was the command `cat README.md` or something else?

**Comment by quackduck** [comment]
This seems to have started happening again after the new API was merged

**Comment by quackduck** [comment]
hasn't been happening in a while so i guess ill close

**Comment by quackduck** [comment]
nvm lol

**Comment by quackduck** [comment]
```
2022/10/27 01:49:25 rpc.go:162: [gRPC] Registering command with name poll
2022/10/27 01:49:25 rpc.go:162: [gRPC] Registering command with name vote
2022/10/27 01:49:25 rpc.go:162: [gRPC] Registering command with name close-poll
2022/10/27 01:49:25 rpc.go:162: [gRPC] Registering command with name create-poll
2022/10/27 01:49:26 rpc.go:57: [gRPC] Registering event listener
2022/10/27 01:49:26 rpc.go:162: [gRPC] Registering command with name correct
2022/10/27 01:49:26 rpc.go:162: [gRPC] Registering command with name math
2022/10/27 01:49:26 rpc.go:162: [gRPC] Registering command with name trivia
2022/10/27 01:49:26 rpc.go:162: [gRPC] Registering command with name counting
fatal error: concurrent map writes

goroutine 58 [running]:
runtime.throw({0xdb406d, 0x0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc000356aa0 sp=0xc000356a70 pc=0x436b71
runtime.mapassign_faststr(0xc0004ec420, 0x0, {0xc00003a348, 0x8})
	/usr/local/go/src/runtime/map_faststr.go:211 +0x39c fp=0xc000356b08 sp=0xc000356aa0 pc=0x41465c
main.(*pluginServer).RegisterCmd(0xc0001ca8f0, 0xc000212d80, {0xf55050, 0xc000256d60})
	/home/ubuntu/devzat/rpc.go:163 +0x136 fp=0xc000356bc0 sp=0xc000356b08 pc=0xbbe8f6
devzat/plugin._Plugin_RegisterCmd_Handler({0xc9f6e0, 0x155dd60}, {0xf51878, 0xc0001ca8f0})
	/home/ubuntu/devzat/plugin/plugin_grpc.pb.go:181 +0xd0 fp=0xc000356c00 sp=0xc000356bc0 pc=0xb46bf0
main.streamInterceptor({0xc9f6e0, 0x155dd60}, {0xf51878, 0xc0001ca8f0}, 0xc15680, 0xe52298)
	/home/ubuntu/devzat/rpc.go:241 +0x74 fp=0xc000356c40 sp=0xc000356c00 pc=0xbbf294
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0000ae000, {0xf58718, 0xc000104d00}, 0xc000380b40, 0xc0000941b0, 0x1510ce0, 0x0)
	/home/ubuntu/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1549 +0xe8e fp=0xc000356e48 sp=0xc000356c40 pc=0xb35d2e
google.golang.org/grpc.(*Server).handleStream(0xc0000ae000, {0xf58718, 0xc000104d00}, 0xc000380b40, 0x0)
	/home/ubuntu/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1624 +0x9e5 fp=0xc000356f68 sp=0xc000356e48 pc=0xb371e5
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/ubuntu/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98 fp=0xc000356fe0 sp=0xc000356f68 pc=0xb31018
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000356fe8 sp=0xc000356fe0 pc=0x4698e1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x294
```

this could be it! working on a fix

**Comment by quackduck** [comment]
if this was the reason it is now fixed. we'll see if this happens again
